=== library-rat/CassetteBeastDamageCalculator/characterSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Characters' Stat",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": { "type": "string" },
      "level": {"type":"integer"},
      "maxHP": { "type": "integer"},
      "mAtk": { "type": "integer"},
      "mDef": { "type": "integer"},
      "rAtk": { "type": "integer"},
      "rDef": { "type": "integer"},
      "speed": { "type": "integer"},
      "signature": { "type" :"boolean"}
    },
    "required": ["name","level","maxHP", "mAtk", "mDef", "rAtk", "rDef", "speed","signature"],
    "additionalProperties": false
  }
}

=== library-rat/CassetteBeastDamageCalculator/Character.json
[
    {
        "name": "Player",
        "level": 200,
        "maxHP" : 120,
        "mAtk" : 100,
        "mDef":	100,
        "rAtk" : 100,
        "rDef":	100,
        "speed": 100,
        "signature": false
    },
    {
        "name": "Kayleigh",
        "level": 200,
        "maxHP" : 144,
        "mAtk" : 100,
        "mDef":	100,
        "rAtk" : 100,
        "rDef":	100,
        "speed": 100,
        "signature": false
    },
    {
        "name": "Meredith",
        "level": 200,
        "maxHP" : 120,
        "mAtk" : 120,
        "mDef":	100,
        "rAtk" : 100,
        "rDef":	100,
        "speed": 100,
        "signature": false
    },
    {
        "name": "Felix",
        "level": 200,
        "maxHP" : 120,
        "mAtk" : 100,
        "mDef":	120,
        "rAtk" : 100,
        "rDef":	100,
        "speed": 100,
        "signature": false
    },
    {
        "name": "Viola",
        "level": 200,
        "maxHP" : 120,
        "mAtk" : 100,
        "mDef":	100,
        "rAtk" : 120,
        "rDef":	100,
        "speed": 100,
        "signature": false
    },
    {
        "name": "Eugene",
        "level": 200,
        "maxHP" : 120,
        "mAtk" : 100,
        "mDef":	100,
        "rAtk" : 100,
        "rDef":	120,
        "speed": 100,
        "signature": false
    },
    {
        "name": "Barkley",
        "level": 200,
        "maxHP" : 120,
        "mAtk" : 100,
        "mDef":	100,
        "rAtk" : 100,
        "rDef":	100,
        "speed": 120,
        "signature": false
    },
    {
        "name": "Sunny",
        "level": 200,
        "maxHP" : 110,
        "mAtk" : 115,
        "mDef":	110,
        "rAtk" : 105,
        "rDef":	95,
        "speed": 105,
        "signature": false
    },
    {
        "name": "Wild Monster",
        "level": 200,
        "maxHP" : 100,
        "mAtk" : 100,
        "mDef":	100,
        "rAtk" : 100,
        "rDef":	100,
        "speed": 100,
        "signature": false
    },
    {
        "name": "Captain",
        "level": 200,
        "maxHP" : 240,
        "mAtk" : 100,
        "mDef":	100,
        "rAtk" : 100,
        "rDef":	100,
        "speed": 100,
        "signature": false
    }
]
