=== library-rat/CassetteBeastDamageCalculator/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Beasts' Stat",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "#": { "type": "integer"},
      "name": { "type": "string" },
      "type": {
        "type": "string",
        "enum": ["beast", "air", "astral", "earth", "fire", "ice", "lightning", "metal", "plant", "plastic", "poison", "water", "glass", "glitter"]
      },
      "maxHP": { "type": "integer"},
      "mAtk": { "type": "integer"},
      "mDef": { "type": "integer"},
      "rAtk": { "type": "integer"},
      "rDef": { "type": "integer"},
      "speed": { "type": "integer"}

    },
    "required": ["#","name", "type", "maxHP", "mAtk", "mDef", "rAtk", "rDef", "speed"],
    "additionalProperties": false
  }
}

=== library-rat/CassetteBeastDamageCalculator/Beast.json
[
    {
        "#" :116,
        "name": "Khepri",
        "type" :"fire",
        "maxHP" : 100,
        "mAtk" : 1,
        "mDef":	100,
        "rAtk" : 300,
        "rDef":	250,
        "speed": 79
    },
    {
        "#" :29,
        "name": "Folklord",
        "type" :"beast",
        "maxHP" : 140,
        "mAtk" : 135,
        "mDef":	135,
        "rAtk" : 100,
        "rDef":	120,
        "speed": 120
    }
]
